version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./:/app
    restart: always
    ports:
      - "80:8000"
    image: app:latest
    container_name: swe599
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    tty: True
